name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Download Dependancies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        build-essential \
        libgtk-3-dev \
        libappindicator3-dev \
        gir1.2-appindicator3-0.1

    - name: Build and Release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}